Added grafana drop down to select host
vdcloudcraft/fail2ban-geo-exporter pull request #2
Opened 2020-05-25 23:09 UTC by Madic-

This adds a drop down menu to the grafana dashboard to select the host on which the exporter is running

2020-05-26 20:22 UTC, vdcloudcraft requested changes
If you can address what I commented inline, I'm happy to approve this.

2020-05-26 20:22 UTC, vdcloudcraft commented on grafana-dash.json
> +        "multi": false,
If you can change `includeAll` and `multi` to `true`, I'll gladly pull this. I prefer to see a total of all my instances and this way we can add a feature without removing another.

2020-05-26 20:52 UTC, vdcloudcraft requested changes
I should have looked closer in my first test of this. Just adding multi-value doesn't do it. The queries need to change, since the host part now looks like `host1|host2`. I'm not sure how to solve this elegantly, other than putting host and port into a single variable. Either way, the queries seem to need adjustments as well.

2020-05-27 18:18 UTC, Madic- commented
I understand your requirement. Will test a bit

2022-04-14 19:27 UTC, closed without merging